version: '3.8'

services:
  wisuda-api:
    build: .
    container_name: wisuda-api
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./DATA:/app/DATA
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - NODE_ENV=production
      - TZ=${TZ:-Asia/Makassar}

  wisuda-cron:
    build: .
    container_name: wisuda-cron
    restart: always
    command: npm run cron
    volumes:
      - ./DATA:/app/DATA
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - NODE_ENV=production
      - TZ=${TZ:-Asia/Makassar}
    depends_on:
      - wisuda-api
