module.exports = {
  apps: [
    {
      name: 'wisuda-api',
      script: 'src/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        TZ: process.env.TZ || 'Asia/Makassar',
      },
      env_production: {
        NODE_ENV: 'production',
        TZ: process.env.TZ || 'Asia/Makassar',
      },
      error_file: './logs/wisuda-api-error.log',
      out_file: './logs/wisuda-api-out.log',
      log_file: './logs/wisuda-api-combined.log',
      time: true,
      max_memory_restart: '500M',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      ignore_watch: ['node_modules', 'logs', 'DATA'],
    },
    {
      name: 'wisuda-cron',
      script: 'src/services/cron.service.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        TZ: process.env.TZ || 'Asia/Makassar',
      },
      env_production: {
        NODE_ENV: 'production',
        TZ: process.env.TZ || 'Asia/Makassar',
      },
      error_file: './logs/wisuda-cron-error.log',
      out_file: './logs/wisuda-cron-out.log',
      log_file: './logs/wisuda-cron-combined.log',
      time: true,
      max_memory_restart: '200M',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
    },
  ],
};