module.exports = {
  apps: [
    {
      name: 'wisuda-api',
      script: 'src/main.js',
      cwd: '/root/wisuda-platform',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        PORT: 8081,
        DB_PATH: '/DATA/AppData/wisuda.db',
        SESSION_SECRET: 'wisuda-secret-change-in-production',
        UPLOAD_PATH: '/DATA/AppData/wisuda-uploads',
        BACKUP_PATH: '/DATA/backups',
        COMPANY_NAME: 'Sorehari Wisuda',
        ADMIN_PHONE: '6282333333420',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 8081,
        DB_PATH: '/DATA/AppData/wisuda.db',
        SESSION_SECRET: 'CHANGE_THIS_IN_PRODUCTION',
        UPLOAD_PATH: '/DATA/AppData/wisuda-uploads',
        BACKUP_PATH: '/DATA/backups',
        COMPANY_NAME: 'Sorehari Wisuda',
        ADMIN_PHONE: '6282333333420',
      },
      error_file: '/var/log/wisuda-api-error.log',
      out_file: '/var/log/wisuda-api-out.log',
      log_file: '/var/log/wisuda-api-combined.log',
      time: true,
      max_memory_restart: '500M',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      ignore_watch: ['node_modules', 'logs', 'DATA'],
    },
    {
      name: 'wisuda-cron',
      script: 'src/services/cron.service.js',
      cwd: '/root/wisuda-platform',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        DB_PATH: '/DATA/AppData/wisuda.db',
        UPLOAD_PATH: '/DATA/AppData/wisuda-uploads',
        BACKUP_PATH: '/DATA/backups',
        COMPANY_NAME: 'Sorehari Wisuda',
        ADMIN_PHONE: '6282333333420',
      },
      env_production: {
        NODE_ENV: 'production',
        DB_PATH: '/DATA/AppData/wisuda.db',
        UPLOAD_PATH: '/DATA/AppData/wisuda-uploads',
        BACKUP_PATH: '/DATA/backups',
        COMPANY_NAME: 'Sorehari Wisuda',
        ADMIN_PHONE: '6282333333420',
      },
      error_file: '/var/log/wisuda-cron-error.log',
      out_file: '/var/log/wisuda-cron-out.log',
      log_file: '/var/log/wisuda-cron-combined.log',
      time: true,
      max_memory_restart: '200M',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
    },
  ],
};